# Generated by Django 5.2.3 on 2025-06-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profession',
            field=models.CharField(choices=[('admin', 'Admin'), ('social media manager', 'Social Media Manager'), ('photographer', 'Photographer'), ('videographer', 'Videographer'), ('photo editor', 'Photo Editor'), ('video editor', 'Video Editor'), ('graphic designer', 'Graphic Designer'), ('finance manager', 'Finance Manager')], max_length=50),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='authapp.client')),
                ('manager', models.ForeignKey(limit_choices_to={'profession': 'social_media_manager'}, on_delete=django.db.models.deletion.CASCADE, to='authapp.employee')),
            ],
        ),
    ]
