# Generated by Django 5.2.3 on 2025-06-27 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_booking_id_alter_employee_profession_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'profession': 'social media manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='authapp.employee'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='service booked', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
