# Generated by Django 5.2.3 on 2025-06-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_booking_manager_booking_service_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='client',
        ),
        migrations.AddField(
            model_name='task',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='authapp.booking'),
        ),
        migrations.AlterField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'profession': 'social media manager'}, on_delete=django.db.models.deletion.CASCADE, to='authapp.employee'),
        ),
    ]
