# Generated by Django 5.2.3 on 2025-06-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_booking_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='authapp.employee'),
        ),
    ]
