# Generated by Django 5.2.3 on 2025-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_employees',
            field=models.ManyToManyField(blank=True, related_name='completed_tasks', to='authapp.employee'),
        ),
    ]
