# Generated by Django 5.2.3 on 2025-06-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_remove_booking_completed_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='timestamp',
            new_name='login_time',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='status',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
